server:
  port: 9090
spring:
  application:
    name: Rich-monitor-admin  #Rich的监控管理员
  profiles:
    active: @profiles.active@

info:
  appName: ${spring.application.name}
  mavenAppName: '@project.artifactId@'
  mavenVersion: '@project.version@'

--- # 监控中心服务端配置
spring:
  boot:
    admin:
      context-path: /admin   # 地址：端口/admin
  security:
    user:
      name: admin         # 进入账号
      password: 123456    # 进入密码


--- # Actuator 监控端点的配置项
management:
  endpoints:
    web:
      # Actuator 提供的 API 接口的根目录。默认为 /actuator
      base-path: /actuator
      exposure:
        # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
        # 生产环境不建议放开所有 根据项目需求放开即可
        include: @endpoints.include@
  endpoint:
    logfile:
      external-file: ./logs/sxpcwlkj-monitor-admin.log


