--- # 监控配置
spring:
  boot:
    admin:
      # Spring Boot Admin Client 客户端的相关配置
      client:
        # 增加客户端开关
        enabled: true
        # 设置 Spring Boot Admin Server 地址
        url: http://172.26.0.130:9090/admin
        instance:
          service-host-type: IP
        username: admin
        password: 123456

--- # 数据库配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.26.0.130:3306/sxpcwlkj?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: sxpcwlkj
    password: PAkAi6mxpNPD4GwJ
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000

--- # 邮件配置
spring:
  mail:
    from: shanpengnian@sxpcwlkj.cn
    host: smtp.ym.163.com # 发件人使用的XX邮箱服务
    username: shanpengnian@sxpcwlkj.cn
    password: spn570104@  # 授权码，不是密码，在qq邮箱设置‐账号里面有生成授权码
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
